const types = {
  UPDATE_LOGIN_CK: 'UPDATE_LOGIN_CK',
  UPDATE_INDEX: 'UPDATE_INDEX',
  UPDATE_GPS: 'UPDATE_GPS',
  UPDATE_SITE: 'UPDATE_SITE',
  UPDATE_LANG: 'UPDATE_LANG',
  UPDATE_ROUTE: 'UPDATE_ROUTE',
  UPDATE_LOGOUT: 'UPDATE_LOGOUT',
  UPDATE_PUSH: 'UPDATE_PUSH',
};

export default types;
